[package]
name = "script-utils"
version = "0.1.0"
authors = ["Arne Beer <contact@arne.beer>"]
edition = "2021"

[lib]
name = "script_utils"
path = "src/lib.rs"

[dependencies]
# Error handling
anyhow = "1"
better-panic = "0.2"

# Shell/cli
shellexpand = "2"
clap = "3.0.0-beta.2"
dirs = "3"

# Process management
subprocess = "0.2"

# Serialization
serde = "1"
serde_derive = "1"
toml = "0.5"

# General purpose
strum = "0.22"
strum_macros = "0.22"
chrono = "0.4"
